set_property PACKAGE_PIN N11 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 20.000 -name sys_clk_pin -waveform {0.000 10.000} -add [get_ports clk]

set_property PACKAGE_PIN K13 [get_ports btn0]
set_property IOSTANDARD LVCMOS33 [get_ports btn0]
set_property PULLDOWN true [get_ports btn0]

set_property PACKAGE_PIN L5 [get_ports {sw[0]}]
set_property PACKAGE_PIN L4 [get_ports {sw[1]}]
set_property PACKAGE_PIN M4 [get_ports {sw[2]}]
set_property PACKAGE_PIN M2 [get_ports {sw[3]}]
set_property PACKAGE_PIN M1 [get_ports {sw[4]}]
set_property PACKAGE_PIN N3 [get_ports {sw[5]}]
set_property PACKAGE_PIN N2 [get_ports {sw[6]}]
set_property PACKAGE_PIN N1 [get_ports {sw[7]}]

set_property PACKAGE_PIN P1 [get_ports {sw[8]}]
set_property PACKAGE_PIN P4 [get_ports {sw[9]}]
set_property PACKAGE_PIN T8 [get_ports {sw[10]}]
set_property PACKAGE_PIN R8 [get_ports {sw[11]}]
set_property PACKAGE_PIN T7 [get_ports {sw[12]}]
set_property PACKAGE_PIN R7 [get_ports {sw[13]}]
set_property PACKAGE_PIN T5 [get_ports {sw[14]}]
set_property PACKAGE_PIN R6 [get_ports {sw[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sw[*]}]

set_property PACKAGE_PIN P5 [get_ports lcd_rs]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rs]

set_property PACKAGE_PIN T3 [get_ports lcd_e]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_e]

set_property PACKAGE_PIN T4 [get_ports {data[0]}]
set_property PACKAGE_PIN T2 [get_ports {data[1]}]
set_property PACKAGE_PIN R3 [get_ports {data[2]}]
set_property PACKAGE_PIN R1 [get_ports {data[3]}]
set_property PACKAGE_PIN R2 [get_ports {data[4]}]
set_property PACKAGE_PIN N4 [get_ports {data[5]}]
set_property PACKAGE_PIN M5 [get_ports {data[6]}]
set_property PACKAGE_PIN P3 [get_ports {data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[*]}]
